CREATE TABLE files(
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    data BYTEA NOT NULL,
    title VARCHAR NOT NULL,
    creation_date timestamp NOT NULL,
    description VARCHAR NOT NULL
)